# Definição de variáveis (ambiente “local” do REST Client)
@base_url = https://fantastic-waffle-qw9rp9x59772xgqw-8080.app.github.dev

### Inserir novo veiculo
POST {{ base_url }}/api/veiculo
Content-Type: application/json

{
  "modelo": "Brasilia",
  "ano": 1980,
  "valor": 20000
}

### Listar todos os veiculos
GET {{ base_url }}/api/veiculo
Accept: application/json

### Buscar veiculos por ID
GET {{ base_url }}/api/veiculo/1
Accept: application/json

### Atualizar veiculo (PUT)
PUT {{ base_url }}/api/veiculo/1
Content-Type: application/json

{
  "nome": "Notebook",
  "quantidade": 09,
  "valor" : 5899.90 
}

### Remover pessoa (DELETE)
DELETE {{ base_url }}/api/veiculo/1
Accept: */*